# docker-compose.yml - AdGuard Home
# Práctica Bloc 4 - Tallafocs (0378)
# Autor: Elnath Lavarino

services:
  adguardhome:
    image: adguard/adguardhome:latest
    container_name: adguardhome
    restart: unless-stopped
    ports:
      # Port DNS - Els clients de la xarxa apunten aquí
      - "53:53/tcp"
      - "53:53/udp"
      # Port panel web d'administració
      - "3000:3000/tcp"
      # Port HTTPS panel web (opcional)
      - "443:443/tcp"
      - "443:443/udp"
      # DNS-over-TLS (DoT)
      - "853:853/tcp"
      # DNS-over-QUIC
      - "784:784/udp"
      - "8853:8853/udp"
    volumes:
      # Volum persistent per a configuració
      - ./adguardhome/work:/opt/adguardhome/work
      # Volum persistent per a dades
      - ./adguardhome/conf:/opt/adguardhome/conf
    networks:
      - adguard_net

networks:
  adguard_net:
    driver: bridge
